version: '3.8'

services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/data # Persist indexed data to host directory
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/data
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama-init.sh:/ollama-init.sh:ro
    entrypoint: [ "/bin/sh", "-c", "/ollama-init.sh" ]
    environment:
      - OLLAMA_HOST=0.0.0.0
      - DEFAULT_OLLAMA_MODELS=gemma:2b
    restart: unless-stopped

  chroma-indexer:
    build: ./chroma-indexer
    container_name: chroma-indexer
    depends_on:
      - chromadb
    volumes:
      - ./chroma-indexer:/app
    env_file:
      - .env
    command: ["sleep", "infinity"]

  cyberlab-api:
    build: ./cyberlab-api
    container_name: cyberlab-api
    ports:
      - "5000:5000"
    depends_on:
      - chromadb
    volumes:
      - ./cyberlab-api:/app
    command: ["python", "server.py"]
    env_file:
      - .env
volumes:
  ollama_data:

